M48
; DRILL file {KiCad 8.0.4} date 2024-10-06T13:03:43-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-06T13:03:43-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X137.676Y-57.415
X143.456Y-57.415
T2
X123.6Y-54.2
X138.4Y-82.4
X162.6Y-55.6
M30
